# Generated by Django 5.1.5 on 2025-01-26 01:06

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=40)),
                ('nazwisko', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50, unique=True)),
                ('opis', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Czytelnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uzytkownik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['uzytkownik__username'],
            },
        ),
        migrations.CreateModel(
            name='Ksiazka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=120)),
                ('rok_publikacji', models.PositiveIntegerField(blank=True, null=True)),
                ('jezyk', models.CharField(choices=[('Polski', 'Polski'), ('Angielski', 'Angielski'), ('Niemiecki', 'Niemiecki'), ('Francuski', 'Francuski'), ('Hiszpański', 'Hiszpański')], default='Angielski', max_length=20)),
                ('status', models.CharField(choices=[('D', 'Dostępna'), ('Z', 'Zarezerwowana'), ('W', 'Wypożyczona')], default='D', max_length=1)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folder_aplikacji.autor')),
                ('kategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='folder_aplikacji.kategoria')),
            ],
            options={
                'ordering': ['tytul'],
            },
        ),
        migrations.CreateModel(
            name='Wypozyczenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wypozyczenia', models.DateField(default=datetime.date.today)),
                ('data_zwrotu', models.DateField(blank=True, null=True)),
                ('czytelnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folder_aplikacji.czytelnik')),
                ('ksiazka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folder_aplikacji.ksiazka')),
            ],
            options={
                'ordering': ['data_wypozyczenia'],
            },
        ),
        migrations.AddField(
            model_name='czytelnik',
            name='wypozyczone_ksiazki',
            field=models.ManyToManyField(blank=True, through='folder_aplikacji.Wypozyczenie', to='folder_aplikacji.ksiazka'),
        ),
    ]
